// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsqpnostsqjdevgcyaqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzcXBub3N0c3FqZGV2Z2N5YXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1Nzk5NDcsImV4cCI6MjA4NDE1NTk0N30.9D45zIMpzw9DNwI6gqVd9--_8Q5u9hxlb2L2_qJjfvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});